export const GET_MOVIE_BY_ID = "GET_MOVIE_BY_ID";
export const GET_MOVIE_BY_ID_SUCCESS = "GET_MOVIE_BY_ID_SUCCESS";
export const GET_MOVIE_BY_ID_FAIL = "GET_MOVIE_BY_ID_FAIL";

export const GET_MOVIE_LIST = "GET_MOVIE_LIST";
export const GET_MOVIE_LIST_SUCCESS = "GET_MOVIE_LIST_SUCCESS";
export const GET_MOVIE_LIST_FAIL = "GET_MOVIE_LIST_FAIL";

